### ISSUE TITLE
Support for tab as a separator

### ISSUE THREAD

**Issue by getflourish** [kumo/sketch-mail-merge#4]
I often have my data in a Google Spreadsheet. It would be great to copy a few columns of data and paste it into Sketch :) Right now, I can’t because its not CSV but TSV.

**Comment by kumo** [comment]
I had a quick look and it looks like I cannot copy and paste directly from Google Spreadsheet -- if I do, the columns are treated as rows. If I copy it into another app like Pages, and then copy that text, it appears as TSV.

**Comment by kumo** [comment]
@getflourish I have added some code in 8f559fdef701fa0fc5839ca814355add59f81637 does that help you?
