### ISSUE TITLE
Vertical alignment with two templates fail

### ISSUE THREAD

**Issue by mushon** [kumo/sketch-mail-merge#5]
Posting this here to make sure it doesn't disappear in the Twitter stream. Unless I misunderstood something I expected that when I select two copies of the template that are positioned one after the other the entries from the CSV will continue to populate under my templates maintaining the relative positioning of the two. Like this:
![screen](http://g.recordit.co/IHUTJh8Ub9.gif)

**Comment by kumo** [comment]
@mushon it seems that this problem occurs when there is no gap between the two groups. If you leave a gap of 1 pixel it works. I will change the plugin so that it works even if there is no gap.

**Comment by mushon** [comment]
I can confirm this works well now. Thanks!
